version: '2'
services:
  cli:
    build:
      context: .
      dockerfile: Dockerfile.builder
    image: builder
    labels:
      lagoon.type: cli
    volumes:
      - ./web:/app/web:delegated
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    labels:
      lagoon.type: nginx-php
      lagoon.name: nginx-php
    volumes:
      - ./web:/app/web:delegated
    depends_on:
      - cli
    environment:
      - AMAZEEIO_URL=drupal-nginx.docker.amazee.io
      - AMAZEEIO=AMAZEEIO
      - AMAZEEIO_HTTP_PORT=8080
    networks:
      - amazeeio-network
      - default
    expose:
      - "8080"
  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    labels:
      lagoon.type: nginx-php
      lagoon.name: nginx-php
## Uncomment the following lines to enable xdebug in php and then restart the php container
#    environment:
#       - XDEBUG_ENABLE=true
    volumes:
      - ./web:/app/web:delegated
    depends_on:
      - cli
  mariadb:
    build:
      context: .
      dockerfile: Dockerfile.mariadb
    labels:
      lagoon.type: mariadb
  redis:
    image: amazeeio/redis
    labels:
      lagoon.type: redis
  varnish:
    image: amazeeio/varnish
    labels:
      lagoon.type: varnish
    expose:
      - "8080"
    environment:
      - AMAZEEIO_URL=drupal.docker.amazee.io
      - AMAZEEIO=AMAZEEIO
      - AMAZEEIO_HTTP_PORT=8080
      - VARNISH_HOST=nginx
    networks:
      - amazeeio-network
      - default
networks:
  amazeeio-network:
    external: true
